# Tool definition @mcp.tool()
from typing import Dict, Any, Optional
from services.search_client import perform_vector_search
from core.logger import get_logger
from core.config import settings

logger = get_logger(__name__)

async def query_knowledge_base(query: str, index_name: Optional[str] = None) -> Dict[str, Any]:
    """
    Searches the internal knowledge base (Sprint Reports, Technical Docs).
    Returns a standardized JSON structure expected by LangGraph workers.
    
    Args:
        query (str): The search query generated by the LLM.
        index_name (str, optional): Target index. Defaults to the environment variable.
    """
    try:
        actual_index = index_name or settings.azure_search_index
        
        logger.info(f"Tool 'query_knowledge_base' invoked for index '{actual_index}' with query: '{query}'")

        # Call the decoupled service layer
        documents = perform_vector_search(query=query, index_name=actual_index)
        
        # Build the standardized JSON response
        return {
            "status": "success",
            "query_info": {
                "original_query": query,
                "target_index": actual_index,
                "results_count": len(documents)
            },
            "documents": documents,
            "message": "Retrieval successful" if documents else "No documents matched the query"
        }

    except Exception as e:
        logger.error(f"Tool execution failed: {str(e)}", exc_info=True)
        # Always return a valid JSON structure, even on failure
        return {
            "status": "error",
            "message": str(e),
            "documents": []
        }